In [1]:
import pandas as pd

In [8]:
col=['name','score']
PPN=pd.read_table('./predicted_socres_PPNet.txt',sep='\t',names=col)
PN=pd.read_table('./predicted_socres_PathNet.txt',sep='\t',names=col)
GN=pd.read_table('./predicted_socres_GGNet.txt',sep='\t',names=col)
###import drivers
cols=['name']
c_drivers=pd.read_table('../../HGDC-master/data/796_drivers.txt',names=cols)
c_drivers

         name
0        EGFR
1         EGF
2      PIK3CA
3      PIK3R1
4         SRC
..        ...
791  KIAA1549
792    SETDB2
793      GRPR
794   CYP19A1
795      GPC5

[796 rows x 1 columns]

In [18]:
### exclude the CDGs,then select top100 gene from each Net
###PPNet
path='/root/rlap-main_fe_gnn/predicted_scores/data/density'
DS1 = set(PPN.iloc[1:, 0]).difference(set(c_drivers.iloc[:, 0]))
DS_PPN = pd.Series(list(DS1))[:100]
DS_PPN.to_csv(path+'DS_PPN.csv')
##PN
DS2 = set(PN.iloc[1:, 0]).difference(set(c_drivers.iloc[:, 0]))
DS_PN = pd.Series(list(DS2))[:100]
DS_PN.to_csv(path+'DS_PN.csv')
##GN
DS3 = set(GN.iloc[1:, 0]).difference(set(c_drivers.iloc[:, 0]))
DS_GN = pd.Series(list(DS3))[:100]
DS_GN.to_csv(path+'DS_GN.csv')

In [19]:
genes = [
    "CDH1", "MTOR", "KMT2B", "HRAS", "TP53", "PTEN", "EP300", "KMT2D", "CREBBP",
    "JUN", "CDKN1A", "NCOR1", "JAK1", "KDM6A", "FGFR3", "KRAS", "BRAF", "AKT1",
    "PIK3R1", "NOTCH1", "STAG2", "RHOA", "CHD4", "HIF1A", "KMT2C", "RB1", "VHL",
    "CTNNB1", "SPOP", "FBXW7", "CCND1", "PIK3CA", "ATM", "MAP2K4", "HLA-A", "HSPA8",
    "MUC16", "IQGAP1", "SMARCA4", "AKAP9", "ITGA2B", "SYNE1", "TNRC6A", "ARID1A",
    "ERCC2", "VWF", "FN1", "TNRC6B", "POLE", "SYK", "TLR4", "NCOA3", "SOS1", "KDR",
    "MED1", "APC", "SMAD4", "TGFBR2", "IGF1R", "FYN", "ATR", "GATA3", "PLCG2", "CASP8",
    "AR", "FGFR2", "BRCA1", "MAP3K1", "STAT3", "MAPK1", "PRKCA", "HGF", "RUNX1", "PLCG1",
    "KAT2B", "NRAS", "EGFR", "KMT2A", "NCOR2", "SRC", "NOTCH2", "PRKDC", "ESR1", "ERBB2"
]
# File path
file_path = '/root/rlap-main_fe_gnn/predicted_scores/data/density/genes_list.txt'

# Writing the list of genes to a text file
with open(file_path, 'w') as file:
    for gene in genes:
        file.write(gene + '\n')

84

In [26]:
####import each net
col=['name1','name2']
GGNet=pd.read_table('/root/HGDC-master/data/GGNet/GGNet.txt',names=col)
GGNet
PPNet=pd.read_table('/root/HGDC-master/data/PPNet/PPNet.txt',names=col)
PPNet
PathNet=pd.read_table('/root/HGDC-master/data/PathNet/PathNet.txt',names=col)
PathNet
###import drivers
c_drivers

         name
0        EGFR
1         EGF
2      PIK3CA
3      PIK3R1
4         SRC
..        ...
791  KIAA1549
792    SETDB2
793      GRPR
794   CYP19A1
795      GPC5

[796 rows x 1 columns]

In [ ]:
for i in genes:
    for j in [GGNet,PPNet,PathNet]:
        print('j')

In [ ]:
for a,i in enumerate(c_drivers['name']):
    print(i)

In [76]:
###compute the interaction with CDGs of each Net
output_file_path='/root/rlap-main_fe_gnn/predicted_scores/data/density/gene_inter_CDGs.txt'
with open(output_file_path, 'w') as file:
    for i in genes:
        list=[]
        for j in [GGNet,PPNet,PathNet]:
            a=j.query('name1=="{}" or name2=="{}"'.format(i,i))
            count_single_gene_Net=0
            for id,k in enumerate(c_drivers['name']):
                c=a.query('name1=="{}" or name2=="{}"'.format(k,k))
                count_single_gene_Net=count_single_gene_Net+len(c)
            list.append(count_single_gene_Net)   
        try:
            file.write(f"{i},{list[0]},{list[1]}, {list[2]}\n")
        except Exception as e:
            print(e)
file.close()

In [19]:
import pandas as pd
import numpy as np
ff=pd.read_table('/root/rlap-main_fe_gnn/predicted_scores/data/boxplot/mean_mutation_matrix.tsv',sep='\t')
filtered_ff=ff[ff['Hugo_Symbol'].isin(['SYNE1','KMT2B','VWF','ITGA2B','IGF1R','RHOA','HLA-A',])]
mean_values = filtered_ff.select_dtypes(include=[np.float_]).mean(axis=1)
mean_values
# filtered_all=ff[~ff['Hugo_Symbol'].isin(['SYNE1','KMT2B','VWF','ITGA2B'])]
filtered_all=ff.select_dtypes(include=[np.float_]).mean()

filtered_all=filtered_all.to_frame().T
filtered_all['Hugo_Symbol']=['all_gene']
filtered_all

,MF: LUAD,MF: READ,MF: UCEC,MF: STAD,MF: PRAD,MF: KIRC,MF: CESC,MF:TGCT,MF: COAD,MF: THCA,MF: BRCA,MF: HNSC,MF: KIRP,MF: BLCA,MF: LIHC,MF: SKCM,Hugo_Symbol
0,0.012979,0.013632,0.038808,0.016284,0.001949,0.003004,0.012077,0.018092,0.000873,0.004307,0.006774,0.000843,0.003197,0.011258,0.00552,0.024717,all_gene

In [20]:
filtered_ff,mean_values

(      Hugo_Symbol  MF: LUAD  MF: READ  MF: UCEC  MF: STAD  MF: PRAD  MF: KIRC  \
 6683        HLA-A  0.006972  0.007027  0.023062  0.036865  0.002018  0.002966
 7070        IGF1R  0.016861  0.000000  0.137920  0.042827  0.008999  0.005922
 7450       ITGA2B  0.024608  0.014622  0.076713  0.033106  0.007850  0.000000
 7953        KMT2B  0.025804  0.044882  0.296359  0.135847  0.007184  0.011875
 9551        MUC16  0.606341  0.339799  0.554555  0.438714  0.058916  0.076464
 10136      NOTCH2  0.042040  0.039888  0.097522  0.067172  0.008486  0.023593
 12832        RHOA  0.008819  0.000000  0.047360  0.047649  0.004038  0.002970
 15175       SYNE1  0.129258  0.333480  0.200673  0.282900  0.048382  0.031092
 17033         VWF  0.048413  0.055541  0.150506  0.077478  0.011615  0.029517

        MF: CESC   MF:TGCT  MF: COAD  MF: THCA  MF: BRCA  MF: HNSC  MF: KIRP  \
 6683   0.067223  0.028915  0.000000  0.001020  0.052980  0.000000  0.010647
 7070   0.019441  0.032381  0.000000  0.015768  0.018840  0.000000  0.003525
 7450   0.010330  0.020270  0.002035  0.006127  0.017743  0.000000  0.007103
 7953   0.055471  0.164278  0.000000  0.014848  0.040932  0.013871  0.007099
 9551   0.257698  0.399334  0.029636  0.134014  0.221660  0.006904  0.094191
 10136  0.039870  0.031633  0.000000  0.025578  0.038813  0.000000  0.028282
 12832  0.013405  0.012865  0.000000  0.006066  0.017678  0.000000  0.000000
 15175  0.136152  0.347480  0.009930  0.063490  0.191363  0.020683  0.050311
 17033  0.055533  0.102298  0.004072  0.015259  0.026759  0.000000  0.007081

        MF: BLCA  MF: LIHC  MF: SKCM
 6683   0.014226  0.008139  0.010012
 7070   0.030260  0.037320  0.035492
 7450   0.033900  0.010956  0.043881
 7953   0.050015  0.043586  0.127469
 9551   0.389205  0.193483  2.196338
 10136  0.025504  0.018710  0.064611
 12832  0.046023  0.000000  0.014086
 15175  0.215949  0.052169  0.238991
 17033  0.040916  0.018631  0.192581  ,
 6683     0.017005
 7070     0.025347
 7450     0.019328
 7953     0.064970
 9551     0.374828
 10136    0.034481
 12832    0.013810
 15175    0.147019
 17033    0.052262
 dtype: float64)

In [3]:
boxplot=pd.concat([filtered_ff,filtered_all]).T
boxplot.to_csv('./data/boxplot/4genes_all.csv')